version: '3'
services:
  orders-db:
    image: postgres:14.3
    restart: always
    container_name: orders
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: 0Rd3rsP4ssw0rd
      POSTGRES_DB: orders
    ports:
      - 5433:5432
  nats:
    image: nats:scratch
    restart: always
    container_name: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222