version: '3'
services:
  nats-server:
    image: nats:scratch
    container_name: nats-server
    ports:
      - "8222:8222"

  client-gateway:
    image: jorgelvelasquez/client-gateway
    container_name: client-gateway
    depends_on: 
      - nats-server
    environment:
      PORT: ${CLIENT_GATEWAY_PORT}
      ORDERS_MICROSERVICES_HOST: ${CLIENT_GATEWAY_ORDERS_MICROSERVICES_HOST}
      ORDERS_MICROSERVICES_PORT: ${CLIENT_GATEWAY_ORDERS_MICROSERVICES_PORT}
      PRODUCTS_MICROSERVICES_HOST: ${CLIENT_GATEWAY_PRODUCTS_MICROSERVICES_HOST}
      PRODUCTS_MICROSERVICES_PORT: ${CLIENT_GATEWAY_PRODUCTS_MICROSERVICES_PORT}
      NATS_SERVERS: ${CLIENT_GATEWAY_NATS_SERVERS}
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}

  # orders-db:
  #   image: postgres:14.3
  #   restart: always
  #   container_name: orders-db
  #   environment:
  #     POSTGRES_USER: ${ORDERS_DB_USER}
  #     POSTGRES_PASSWORD: ${ORDERS_DB_PASSWORD}
  #     POSTGRES_DB: ${ORDERS_DB}
  #   ports:
  #     - 5433:5432

  orders-ms:
    image: jorgelvelasquez/orders-ms
    container_name: orders-ms
    depends_on:
      - orders-db
      - nats-server
    environment:
      PORT: ${ORDERS_PORT}
      PRODUCTS_MICROSERVICES_HOST: ${ORDERS_PRODUCTS_MICROSERVICES_HOST} 
      PRODUCTS_MICROSERVICES_PORT: ${ORDERS_PRODUCTS_MICROSERVICES_PORT}
      NATS_SERVERS: ${ORDERS_NATS_SERVERS}
      DATABASE_URL: ${ORDERS_DATABASE_URL}

  products-ms:
    image: jorgelvelasquez/products-ms
    container_name: products-ms
    depends_on:
      - nats-server
    environment:
      PORT: ${PRODUCTS_PORT}
      NATS_SERVERS: ${PRODUCTS_NATS_SERVERS}
      DATABASE_URL: ${PRODUCTS_DATABASE_URL}

  payments-ms:
    image: jorgelvelasquez/payments-ms
    container_name: payments-ms
    depends_on:
      - nats-server
    environment:
      PORT: ${PAYMENTS_PORT}
      NATS_SERVERS: ${PAYMENTS_NATS_SERVERS}
    ports:
      - ${PAYMENTS_PORT}:${PAYMENTS_PORT}

  auth-ms:
    image: jorgelvelasquez/auth-ms
    container_name: auth-ms
    depends_on:
      - nats-server
    environment:
      PORT: ${AUTH_PORT}
      NATS_SERVERS: ${AUTH_NATS_SERVERS}
      DATABASE_URL: ${AUTH_DATABASE_URL}
      JWT_SECRET: ${AUTH_JWT_SECRET}
      JWT_EXPIRES_IN: ${AUTH_JWT_EXPIRES_IN}
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}